### PR TITLE
updated README, updated deps to address audit, changed to audit-ci on Travis

### PR DESCRIPTION
**Pull request by schwarrrtz**

### CODE REVIEW

**Comment by schwarrrtz** [comment]
Looks like `npm audit` is failing on Travis:

```
found 212 vulnerabilities (7 low, 204 moderate, 1 high) in 2123 scanned packages

  run `npm audit fix` to fix 211 of them.

  1 vulnerability requires manual review. See the full report for details.

The command "npm audit --audit-level=high" exited with 1.
```

not sure what to do about this...

**Comment by trisapeace** [comment]
@schwarrrtz , It found a security issue in one of our dependencies. So you'll need to fix it before it will pass. You can try running `npm audit fix` as it suggests and that will bump minor versions if that will fix it. Hopefully the one that `npm audit fix` can't fix won't be the high severity one that is blocking the build. But you can run `npm audit` locally and get some output as to what the problem is, normally there is a link with more details about the issue and also about how to fix it. Let me know if you still have problems.

**Comment by schwarrrtz** [comment]
welp, there are now 5 high severity vulnerabilities, and `npm audit fix` will only work for 2 of them. I'm looking into manual fixes

**Comment by trisapeace** [comment]
OK thanks. If it looks too bad, we can up the blocking requirements on `npm audit` level to `critical` or even take it out. I like the idea of static security scans like this, but maybe it's too much of a pain for right now.

**Comment by schwarrrtz** [comment]
ok so I addressed most of the vulnerabilities with `npm audit fix` and increased the minSdkVersion to fix the following error (which resulted from an update to `react-native` made by the aforementioned command):

`Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.64.2]`

after a discussion with @trisapeace I also changed the audit command to use `audit-ci` when running on Travis to give us the option to exclude certain vulnerabilities from the audit. I excluded #1754 (a DoS vulnerability in css-what) because it only affects our SVG library - it's hard to imagine how someone could inject malicious content into our SVGs, and even if that did happen the impact would be relatively low (the app would run slowly or stall on users' devices, but no user data would be compromised). we should revisit this once `react-native-svg` gets updated to use a newer version of `css-what`.

**Review by trisapeace — APPROVED** [review]
Looks good to me, but I think it's worth adding something to the CHANGELOG about this.

**Pull request merged**
