### PR TITLE
added notifications counting for Sensors (CU-hjwcwk)

### PR DESCRIPTION
**Pull request by schwarrrtz**
this pull request adds the connection to the Sensors backend when counting notifications.

testing notes:

- the automated tests passed on Travis when pushing the branch to Github
- I tested this on an Android emulator connected to the backend development environments for Buttons and Sensors. everything seems to work as expected.

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-hjwcwk Frontend & Backend: Implementation of notification counting](https://app.clickup.com/t/hjwcwk)

**Comment by schwarrrtz** [comment]
darn, there's a new vulnerability that is causing audit-ci to fail the build on Travis.

**Review by trisapeace — APPROVED** [review]
This looks good to me, even with the security failure. I'll figure it out as part of #20 .

**Comment by schwarrrtz** [comment]
ok sounds good.

**Pull request merged**
